---
########################## dev
spring:
  profiles: dev
server:
  port: 8082
logging:
  level:
    org:
      springframework:
        security: DEBUG
security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:8081/oauth/token_key

