---
########################## dev
spring:
  profiles: dev
  redis:
    host: 127.0.0.1
    port: 6379
    pool: 
      max-active: 20
      max-wait: 1
      max-idle: 10
      min-idle: 1
    database: 0  
server:
  port: 8082
logging:
  level:
    org:
      springframework:
        security: DEBUG
security:
  oauth2:
    client:
      client-id: 1d904b75-172f-11ea-bac1-000c299d55e0
      client-secret: 123456
    resource:
      prefer-token-info: true
      token-info-uri: http://localhost:8081/oauth/check_token
      user-info-uri: http://localhost:8081/check/user
#      jwt:
#        key-uri: http://localhost:8081/oauth/token_key

