---
########################## dev
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #url: jdbc:mysql://192.168.0.24:3306/vanda_zhxq_pt?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    #username:  dbuser
    #password:  10121416
    url: jdbc:mysql://192.168.0.113:3306/platform_oauth2_server?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: hecheng #root
    password: 123456 #root
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 10
    minIdle: 10
    maxActive: 200
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: 127.0.0.1
    port: 6379
    pool: 
      max-active: 20
      max-wait: 1
      max-idle: 10
      min-idle: 1
    database: 0
hystrix:
  metrics:
    enabled: true
server:
  port: 8081
#忽略的接口
author:
  ignoreApiUrls: /oauth/token,/v1/**
#系统中不能删除的角色
roles:
  deleteDeny: ADMIN
logging:
  level:
    org:
      springframework:
        security: DEBUG

