---
########################## dev
debug: true
server:
  port: 8080
  tomcat:
    basedir: E:/test/tomcatfiletemp
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/security?characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa: 
    show-sql: true
    generate-ddl: false
    database: MYSQL
    hibernate: 
      ddl-auto: update
author:
  ignoreUrls: /,/home,/error,/swagger/**,/v2/api-docs,/v1/security/loginFail,/v1/security/loginSuccess,/login
roles: 
  deleteDeny: admin
swagger: 
  version: 1

